---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: {{ env "APPNAME" }}-budget
  namespace: {{ env "REPONAME" }}
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{ env "APPNAME" }}
