---
apiVersion: v1
kind: Service
metadata:
  name: {{ env "REPONAME" }}
  namespace: {{ env "REPONAME" }}
  labels:
    app: {{ env "REPONAME" }}
  annotations:
    external-dns.alpha.kubernetes.io/hostname: {{ env "REPONAME" }}.{{ env "ENV" }}.medialaben.no.
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: http-port
  selector:
    app: {{ env "REPONAME" }}
